version: "3"
services: 
    redis-service:
        container_name: redis-service-composed
        image: redis
        ports:
            - "7001:6379"
        networks:
            - back-tier
    
    cache-service:
        container_name: cache-service
        image: cache-service:latest
        ports:
          - "7000:7700"
        networks:
            - front-tier
            - back-tier

networks:
  front-tier: {}
  back-tier: {}